window.onload = function () {
document.getElementById('io_arrow').innerHTML = "&rarr;";
document.getElementById('level').innerHTML = "&#9733; &#9734; ";
document.getElementById('ptitle').innerHTML = "整数列の整列";
document.getElementById('ptitle_en').innerHTML = "Sorting Integers";
document.getElementById('input_comment').innerHTML = "整数の列<ul><li>$N &le; 100$</li><li> $a_i &le; 10^9$</li></ul>";
document.getElementById('output_comment').innerHTML = "整列された整数の列";
document.getElementById('motivation').innerHTML = "データをそれらがもつある共通のキーを基準に整列することは情報処理の基本です。ここでは、要素数が比較的少ない、整数の列を整列することを考えます。";
document.getElementById('description').innerHTML = "整数の列{a_0, a_1, ..., a_N}を小さい順に並べ替えてください。";
document.getElementById('input_panel').innerHTML = '<img src="../../problems/sort_small/input.svg" width="340"/>';
document.getElementById('output_panel').innerHTML = '<img src="../../problems/sort_small/output.svg" width="340"/>';
document.getElementById('algorithm_icon').innerHTML = '<img src="../../icons/algorithms/selection_sort.svg" width="100"/>';
document.getElementById('atitle').innerHTML = "選択ソート";
document.getElementById('atitle_en').innerHTML = "Selection Sort";
document.getElementById('abstract').innerHTML = "選択ソートは、配列を前方のソート済み部分と後方の未ソート部分に分け、未ソート部分から最小値を探索し、未ソートの部分の先頭とスワップすることで、ソート済み部分へ追加していきます。";
document.getElementById('explanation').innerHTML = "前方から１つずつソート済みの要素を決定していきます。未ソートの部分を対象にminimum(A, i, N)によって配列Aの区間[i, N)の要素の中で最小値の位置minjを特定し、その要素と未ソートの部分の先頭をスワップします。このとき、選択された要素が拡張されたソート済み部分に移動します。";
document.getElementById('note').innerHTML = "１番小さい要素を先頭に移動するための最小値探索では比較が$N-1$回、２番目に小さい要素をソート済み部分の末尾へ移動するために比較を$N-2$回、...、という具合に最小値探索を$N$回行います。よって全体の比較・スワップ回数の総数は($N-1$) + ($N-2$) + ,.., $+ 1 = N(N-1)/2$回となり、オーダーはO($N^2$)となります。";
document.getElementById('application').innerHTML = "選択ソートは、最も素朴なソートアルゴリズムのひとつです。計算効率が悪いため、実用的ではありませんが、直観的な操作のため、初等的アルゴリズムの導入として適しています。";
document.getElementById('structure').innerHTML = '<tr><td style="text-align:center;width:100"><img src="../../icons/structures/A1D.svg" /><br/><br/></td><td class="frame">&nbsp;<img height="160" class="frame_svg" valign="middle" src="space_st.svg" />&nbsp;</td></tr><tr><td></td><td class="caption">１次元配列</td></tr>';
document.getElementById('variable').innerHTML = '<tr><th class="scene_desc" colspan="3">データ</th></tr><tr><td class="symbol"><img src="variable_A.svg" /></td><td>整数の列</td><td class="code">A</td></tr>';
document.getElementById('formula').innerHTML = '<tr><th class="scene_desc" colspan="3">入力</th></tr><tr><td class="symbol"><img src="formula_in.svg" /></td><td>整数の列を入力します。</td><td class="code"></td></tr><tr><th class="scene_desc" colspan="3">整列</th></tr><tr><td class="symbol"><img src="formula_comp.svg" /></td><td>未ソート部分から最小値を探します。</td><td class="code">minj &larr; minimum(A, i, N)</td></tr><tr><td class="symbol"><img src="formula_cp.svg" /></td><td>最小値を指します。</td><td class="code">minj</td></tr><tr><td class="symbol"><img src="formula_w.svg" /></td><td>未ソートの部分の先頭と最小値をスワップします。</td><td class="code">swap(A[i], A[minj])</td></tr><tr><td class="symbol"><img src="formula_sorted.svg" /></td><td>ソート済みの範囲を拡張していきます。</td><td class="code">区間[0, i)</td></tr><tr><th class="scene_desc" colspan="3">出力</th></tr><tr><td class="symbol"><img src="formula_out.svg" /></td><td>整列された整数の列を出力します。</td><td class="code"></td></tr>';
document.getElementById('scheme').innerHTML = '<tr><td style="text-align:center;width:100"><img src="anim_qr.svg" width="80"/></td><td class="frame"><hr class="separator"/><img height="160" class="frame_svg" src="scheme_step1.svg" /><p class="caption">未ソートの部分から最小値の位置を探します。</p><hr class="separator"/><img height="160" class="frame_svg" src="scheme_step2.svg" /><p class="caption">未ソートの先頭と最小値をスワップします。</p></td></tr>';
document.getElementById('scene').innerHTML = '<div><p><b class="scene_desc">入力</b><br/><img src="scene_0.svg" alt="選択ソート | 入力" title="選択ソート | 入力"/></p></div><div><p><b class="scene_desc">整列</b><br/><img src="scene_1.svg" alt="選択ソート | 整列" title="選択ソート | 整列"/></p></div><div><p><b class="scene_desc">出力</b><br/><img src="scene_2.svg" alt="選択ソート | 出力" title="選択ソート | 出力"/></p></div>';
document.getElementById('complexity').innerHTML = '<img src="../../../icons/complexity/quad.svg" />';
document.getElementById('prerequisites').innerHTML = '<img src="../../icons/algorithms/minimum_of_integers_index.svg" width="60"/><img src="../../icons/algorithms/swap.svg" width="60"/>';
MathJax.Hub.Queue(["Typeset",MathJax.Hub]);};