window.onload = function () {
document.getElementById('io_arrow').innerHTML = "&rarr;";
document.getElementById('level').innerHTML = "&#9733; ";
document.getElementById('ptitle').innerHTML = "新增元素到已排序的序列中";
document.getElementById('ptitle_en').innerHTML = "(Add an Element to Sorted Sequence)";
document.getElementById('input_comment').innerHTML = "已升冪排列的序列，最後 1 個元素為<ul><li>要插入的元素<ul><li>元素數 N &le; 100</li></ul>";
document.getElementById('output_comment').innerHTML = "插入 1 個元素後，並經過排序的序列";
document.getElementById('motivation').innerHTML = "以下將介紹如何在升冪排序的序列中新增 1 個元素，並維持序列的升冪狀態。";
document.getElementById('description').innerHTML = "加入1個元素後，保持序列的升冪狀態。";
document.getElementById('input_panel').innerHTML = '<img src="../../problems/insertion/input.svg" width="340"/>';
document.getElementById('output_panel').innerHTML = '<img src="../../problems/insertion/output.svg" width="340"/>';
document.getElementById('algorithm_icon').innerHTML = '<img src="../../icons/algorithms/insertion.svg" width="100"/>';
document.getElementById('atitle').innerHTML = "插入";
document.getElementById('atitle_en').innerHTML = "Insertion";
document.getElementById('abstract').innerHTML = "準備 1 個臨時變數 t 以暫存要插入的值，並從序列的尾端開始往前尋找可插入 t 值的位置。若遇到的元素比 t 值大，便將其往後移動（複製）1 個位置。若遇到的元素比 t 值小，則將 t 值放到該元素後方的位置，插入操作便完成了。";
document.getElementById('explanation').innerHTML = "要改變陣列元素的排列方式時，我們可以在陣列以外，準備一個方便計算的臨時變數。插入元素的做法是，先將陣列最尾端的插入值暫存到臨時變數 t，再由後往前於已排序的部分尋找可插入 t 值的位置。此過程中，若是遇到的元素值比 t 值大，便將其往後移動（複製）1 個位置。若遇到的元素值比 t 值小，則將 t 值放到該元素後方的位置，這樣就完成插入的操作了。若插入值為最小值，則所有元素都將被往後移動 1 個位置，而插入值會放在陣列的最前端。";
document.getElementById('note').innerHTML = "在插入操作中，比插入值大的元素都必須往後移動。因此最差情況就是插入值比所有元素都小，每個元素都必須往後移動。這表示插入操作的時間複雜度為 O(N)。在接下來的章節中，我們會直接使用 insertion(A, i) 函式進行插入操作，將陣列 A 最尾端的元素 i 插入到陣列。";
document.getElementById('application').innerHTML = "insertion 函式是「插入排序法」中的基本操作。";
document.getElementById('structure').innerHTML = '<tr><td style="text-align:center;width:100"><img src="../../icons/structures/A1D.svg" /><br/><br/><img src="../../icons/structures/A0D.svg" /><br/><br/></td><td class="frame">&nbsp;<img height="160" class="frame_svg" valign="middle" src="space_st.svg" />&nbsp;</td></tr><tr><td></td><td class="caption">一維陣列與單節點</td></tr>';
document.getElementById('variable').innerHTML = '<tr><th class="scene_desc" colspan="3">資料</th></tr><tr><td class="symbol"><img src="variable_A.svg" /></td><td>整數序列</td><td class="code">A</td></tr><tr><td class="symbol"><img src="variable_t.svg" /></td><td>暫時存放要插入的值</td><td class="code">t</td></tr>';
document.getElementById('formula').innerHTML = '<tr><th class="scene_desc" colspan="3">輸入</th></tr><tr><td class="symbol"><img src="formula_in.svg" /></td><td>輸入整數序列。</td><td class="code"></td></tr><tr><td class="symbol"><img src="formula_b.svg" /></td><td>暫時存放插入值。</td><td class="code"></td></tr><tr><th class="scene_desc" colspan="3">插入</th></tr><tr><td class="symbol"><img src="formula_select.svg" /></td><td>比較目前位置的值與插入值。</td><td class="code">if A[j] > t:</td></tr><tr><td class="symbol"><img src="formula_cp.svg" /></td><td>表示目前位置的值比插入值大，因此要將該值往後方移動。</td><td class="code">j</td></tr><tr><td class="symbol"><img src="formula_jp.svg" /></td><td>用前 1 個元素的值覆蓋掉原本的值。</td><td class="code">A[j+1] &larr; A[j]</td></tr><tr><td class="symbol"><img src="formula_sorted.svg" /></td><td擴大已排序完成的範圍。</td><td class="code">區間[j+1, N)</td></tr><tr><th class="scene_desc" colspan="3">輸出</th></tr><tr><td class="symbol"><img src="formula_out.svg" /></td><td>輸出排序完成的序列。</td><td class="code"></td></tr>';
document.getElementById('scheme').innerHTML = '<tr><td style="text-align:center;width:100"><img src="anim_qr.svg" width="80"/></td><td class="frame"><hr class="separator"/><img height="160" class="frame_svg" src="scheme_step1.svg" /><p class="caption">比較兩個值，確認是否可以插入。</p><hr class="separator"/><img height="160" class="frame_svg" src="scheme_step2.svg" /><p class="caption">目前位置的值（5）比插入值（3）大，所以要往後方移動。</p><hr class="separator"/><img height="160" class="frame_svg" src="scheme_step3.svg" /><p class="caption">將要插入的元素放到序列中。</p></td></tr>';
document.getElementById('scene').innerHTML = '<div><p><b class="scene_desc">入力</b><br/><img src="scene_0.svg" alt="插入 | 輸入" title="插入 | 輸入"/></p></div><div><p><b class="scene_desc">插入</b><br/><img src="scene_1.svg" alt="插入 | 插入" title="插入 | 插入"/></p></div><div><p><b class="scene_desc">輸出</b><br/><img src="scene_2.svg" alt="插入 | 輸出" title="插入 | 輸出"/></p></div>';
document.getElementById('complexity').innerHTML = '<img src="../../../icons/complexity/linear.svg" />';
document.getElementById('prerequisites').innerHTML = '';
MathJax.Hub.Queue(["Typeset",MathJax.Hub]);};