window.onload = function () {
document.getElementById('io_arrow').innerHTML = "&rarr;";
document.getElementById('level').innerHTML = "&#9733; &#9733; ";
document.getElementById('ptitle').innerHTML = "素数表";
document.getElementById('ptitle_en').innerHTML = "Prime Number Table";
document.getElementById('input_comment').innerHTML = "１つの整数N <ul><li>2 &le; N &le; 1,000,000</li></ul>";
document.getElementById('output_comment').innerHTML = "Nまでの素数表";
document.getElementById('motivation').innerHTML = "素数とは、１とその数自身以外に約数が存在しない正の整数です。素数の性質は暗号や高速なアルゴリズムの実装などで応用されるため、素数かどうかの判定や素数生成には、効率の良いアルゴリズムが求められます。";
document.getElementById('description').innerHTML = "整数iが素数のときi番目の要素が1、合成数のとき0となるような素数表を作成してください。";
document.getElementById('input_panel').innerHTML = '<img src="../../problems/prime_number_table/input.svg" width="340"/>';
document.getElementById('output_panel').innerHTML = '<img src="../../problems/prime_number_table/output.svg" width="340"/>';
document.getElementById('algorithm_icon').innerHTML = '<img src="../../icons/algorithms/sieve_of_eratosthenes.svg" width="100"/>';
document.getElementById('atitle').innerHTML = "エラトステネスの篩";
document.getElementById('atitle_en').innerHTML = "Sieve of Eratosthenes";
document.getElementById('abstract').innerHTML = "エラトステネスの篩は、サイズNの配列を素数表として扱い、2から(N-1)までの素数を列挙するアルゴリズムです。";
document.getElementById('explanation').innerHTML = "エラトステネスの篩のアルゴリズムは主に３つのフェーズから成ります。最初のフェーズで、2以上の整数を素数の候補とします。次のフェーズで、2を残して2より大きい2の倍数(4, 6, 8, ...)を篩って候補から外します。最後のフェーズで、奇数iについて、iを残してiの倍数を篩って候補から外していきます。<br><br>奇数iを素数としてその倍数を合成数とした後は、2から$i^2$までの素数表が確定します。例えば、5を残してその倍数を全て篩った後は、25までの素数表が確定します（仮にこの時点で6から25までの中に合成数が存在するのであれば、そのペアとなる数が5以下の数に存在するはずです）。同様の原理で、奇数iの倍数を篩う処理は、iがNの平方根まで調べれば十分です。";
document.getElementById('note').innerHTML = "エラトステネスの篩の計算量はO($N $log^2 N$)であることが知られています。";
document.getElementById('application').innerHTML = "素数は暗号化など、様々なアプリケーションで応用されるため、素数表の作成や素数判定を高速に行うエラトステネスの篩と関連アルゴリズムは、セキュリティの分野などで使用されます。また、セキュリティ分野に限らず、乱数を生成するアルゴリズムやデータ構造の実装でも素数が使われます。";
document.getElementById('structure').innerHTML = '<tr><td style="text-align:center;width:100"><img src="../../icons/structures/A1D.svg" /><br/><br/></td><td class="frame">&nbsp;<img height="160" class="frame_svg" valign="middle" src="space_a.svg" />&nbsp;</td></tr><tr><td></td><td class="caption">一次元配列</td></tr>';
document.getElementById('variable').innerHTML = '<tr><th class="scene_desc" colspan="3">データ</th></tr><tr><td class="symbol"><img src="variable_P.svg" /></td><td>P[i]が1のときiが素数である素数表</td><td class="code">P</td></tr>';
document.getElementById('formula').innerHTML = '<tr><th class="scene_desc" colspan="3">初期化</th></tr><tr><td class="symbol"><img src="formula_ini.svg" /></td><td>2以上の数を素数の候補として初期化します。</td><td class="code"></td></tr><tr><th class="scene_desc" colspan="3">2の倍数を削除</th></tr><tr><td class="symbol"><img src="formula_s.svg" /></td><td>2の倍数を合成数とします。</td><td class="code">P[j] &larr; 0</td></tr><tr><th class="scene_desc" colspan="3">奇数の素数の倍数を削除</th></tr><tr><td class="symbol"><img src="formula_decision.svg" /></td><td>素数として残します。</td><td class="code">i</td></tr><tr><td class="symbol"><img src="formula_s.svg" /></td><td>残した数の倍数を合成数とします。</td><td class="code">P[j] &larr; 0</td></tr><tr><td class="symbol"><img src="formula_valid.svg" /></td><td>素数表を確定します。</td><td class="code">区間[0, i*i]</td></tr><tr><th class="scene_desc" colspan="3">素数リストを出力</th></tr><tr><td class="symbol"><img src="formula_prime.svg" /></td><td>素数を列挙します。</td><td class="code"></td></tr>';
document.getElementById('scheme').innerHTML = '<tr><td style="text-align:center;width:100"><img src="anim_qr.svg" width="80"/></td><td class="frame"><hr class="separator"/><img height="160" class="frame_svg" src="scheme_step.svg" /><p class="caption">倍数を削除します。</p></td></tr>';
document.getElementById('scene').innerHTML = '<div><p><b class="scene_desc">初期化</b><br/><img src="scene_0.svg" alt="エラトステネスの篩 | 初期化" title="エラトステネスの篩 | 初期化"/></p></div><div><p><b class="scene_desc">2の倍数を削除</b><br/><img src="scene_1.svg" alt="エラトステネスの篩 | 2の倍数を削除" title="エラトステネスの篩 | 2の倍数を削除"/></p></div><div><p><b class="scene_desc">奇数の素数の倍数を削除</b><br/><img src="scene_2.svg" alt="エラトステネスの篩 | 奇数の素数の倍数を削除" title="エラトステネスの篩 | 奇数の素数の倍数を削除"/></p></div><div><p><b class="scene_desc">素数リストを出力</b><br/><img src="scene_3.svg" alt="エラトステネスの篩 | 素数リストを出力" title="エラトステネスの篩 | 素数リストを出力"/></p></div>';
document.getElementById('complexity').innerHTML = '<img src="../../../icons/complexity/linear_log.svg" />';
document.getElementById('prerequisites').innerHTML = '';
MathJax.Hub.Queue(["Typeset",MathJax.Hub]);};