window.onload = function () {
document.getElementById('io_arrow').innerHTML = "&rarr;";
document.getElementById('level').innerHTML = "&#9733; &#9733; ";
document.getElementById('ptitle').innerHTML = "二分木の巡回：左の子・親優先";
document.getElementById('ptitle_en').innerHTML = "Traversal on Binary Tree: Left Child-Parent First";
document.getElementById('input_comment').innerHTML = "二分木<ul><li>ノードの数 N &le; 100,000</li></ul>";
document.getElementById('output_comment').innerHTML = "親の前に左の子の子孫、親の後に右の子の子孫が訪問される訪問順";
document.getElementById('motivation').innerHTML = "親子の順番だけでなく、親を挟んだ兄弟にも優先順を付けた巡回は、ノードの値に大小関係の条件が付くデータ構造で重要な役割を果たします。";
document.getElementById('description').innerHTML = "二分木のノードを次の条件を満たすように訪問してください：親が左の子の後、右の子の前に訪問される。";
document.getElementById('input_panel').innerHTML = '<img src="../../problems/btree_inorder/input.svg" width="340"/>';
document.getElementById('output_panel').innerHTML = '<img src="../../problems/btree_inorder/output.svg" width="340"/>';
document.getElementById('algorithm_icon').innerHTML = '<img src="../../icons/algorithms/btree_inorder.svg" width="100"/>';
document.getElementById('atitle').innerHTML = "中間順巡回";
document.getElementById('atitle_en').innerHTML = "In-order Traversal";
document.getElementById('abstract').innerHTML = "中間順巡回アルゴリズムは二分木のノードを左部分木、節点、右部分木の順に訪問します。二分木の各ノードに、中間順巡回で訪問した順番を印字していきます。";
document.getElementById('explanation').innerHTML = "inorder(t, u)を二分木tのノードuを訪問する再帰関数とすると、中間順巡回は、inorder(t, uの左の子)で左部分木のノードを訪問した後に、uを印字し、その後にinorder(t, uの右の子）で右部分木のノードを順番に訪問します。";
document.getElementById('note').innerHTML = "二分木の巡回では、各ノードが一度訪問されるので、オーダーはO(N)となります。";
document.getElementById('application').innerHTML = "中間順巡回アルゴリズムでは、親が左の子の後、右の子の前に処理されます。この特徴は、データの大小関係を維持する二分探索木の要素を、値の昇順にアクセスするアルゴリズムとして応用されます。";
document.getElementById('structure').innerHTML = '<tr><td style="text-align:center;width:100"><img src="../../icons/structures/BT.svg" /><br/><br/></td><td class="frame">&nbsp;<img height="160" class="frame_svg" valign="middle" src="space_t.svg" />&nbsp;</td></tr><tr><td></td><td class="caption">二分木</td></tr>';
document.getElementById('variable').innerHTML = '<tr><th class="scene_desc" colspan="3">データ</th></tr><tr><td class="symbol"><img src="variable_L.svg" /></td><td>訪問した順番</td><td class="code">L</td></tr>';
document.getElementById('formula').innerHTML = '<tr><th class="scene_desc" colspan="3">二分木の巡回</th></tr><tr><td class="symbol"><img src="formula_visit.svg" /></td><td>ノードを訪問して順番のラベルをつけます。</td><td class="code">L[u] &larr; time++</td></tr><tr><td class="symbol"><img src="formula_visited.svg" /></td><td>訪問済みのノードを拡張していきます。</td><td class="code">L[u]が設定されたノード</td></tr>';
document.getElementById('scheme').innerHTML = '<tr><td style="text-align:center;width:100"><img src="anim_qr.svg" width="80"/></td><td class="frame"><hr class="separator"/><img height="160" class="frame_svg" src="scheme_step1.svg" /><p class="caption">ノードを訪問します。</p></td></tr>';
document.getElementById('scene').innerHTML = '<div><p><b class="scene_desc">二分木の巡回</b><br/><img src="scene_0.svg" alt="中間順巡回 | 二分木の巡回" title="中間順巡回 | 二分木の巡回"/></p></div>';
document.getElementById('complexity').innerHTML = '<img src="../../../icons/complexity/linear.svg" />';
document.getElementById('prerequisites').innerHTML = '';
MathJax.Hub.Queue(["Typeset",MathJax.Hub]);};