window.onload = function () {
document.getElementById('io_arrow').innerHTML = "&rarr;";
document.getElementById('level').innerHTML = "&#9734; ";
document.getElementById('ptitle').innerHTML = "２つの要素の交換";
document.getElementById('ptitle_en').innerHTML = "Swapping Two Elements";
document.getElementById('input_comment').innerHTML = "順序がある２つの整数";
document.getElementById('output_comment').innerHTML = "順番を入れ替えた２つの整数";
document.getElementById('motivation').innerHTML = "アルゴリズムの最も基本的な操作は、変数（メモリ）に対するデータの読み書きです。データの読み書きの組み合わせが必要な「入れ替え」問題は、データの並び替えなどの基本操作として多くのアルゴリズムに現れます。";
document.getElementById('description').innerHTML = "異なる２つの変数の値を入れ替えてください。";
document.getElementById('input_panel').innerHTML = '<img src="../../problems/swap/input.svg" width="340"/>';
document.getElementById('output_panel').innerHTML = '<img src="../../problems/swap/output.svg" width="340"/>';
document.getElementById('algorithm_icon').innerHTML = '<img src="../../icons/algorithms/swap.svg" width="100"/>';
document.getElementById('atitle').innerHTML = "スワップ";
document.getElementById('atitle_en').innerHTML = "Swap";
document.getElementById('abstract').innerHTML = "変数の中身を交換する処理をスワップと言います。スワップ処理には、２つの変数以外に、どちらかの値を退避しておくためのもうひとつの変数が必要になります。";
document.getElementById('explanation').innerHTML = "２つの変数の中身を交換するには、まず1つ目の変数の値を、2つ目の変数ではない別の変数に一時的に退避します。変数の上書きによってデータが消滅してしまうのを避けるために「退避」します。次に、１つ目の変数に２つ目の変数の値を書き込んだ後に（この時点で２つの変数には同じ値が入っています）、退避しておいた値を2つ目の変数に書き込み交換処理が終了します。";
document.getElementById('note').innerHTML = "以降はこの処理を関数swap(a, b)として利用します。このswap関数は、変数のアドレスを渡すタイプで、swap(a, b)が実行されると、変数aと変数bの値が入れ替わるものとします。";
document.getElementById('application').innerHTML = "スワップは、データの列を管理する配列の要素に対して行われることが多く、データを整列するアルゴリズムやデータ構造の操作などに使用される汎用的な処理です。";
document.getElementById('structure').innerHTML = '<tr><td style="text-align:center;width:100"><img src="../../icons/structures/A0D.svg" /><br/><br/></td><td class="frame">&nbsp;<img height="160" class="frame_svg" valign="middle" src="space_st.svg" />&nbsp;</td></tr><tr><td></td><td class="caption">３つのシングルノード</td></tr>';
document.getElementById('variable').innerHTML = '<tr><td class="symbol"><img src="variable_a.svg" /></td><td>１つ目の整数</td><td class="code">a</td></tr><tr><td class="symbol"><img src="variable_b.svg" /></td><td>２つ目の整数</td><td class="code">b</td></tr><tr><td class="symbol"><img src="variable_t.svg" /></td><td>一時的に退避された整数</td><td class="code">t</td></tr>';
document.getElementById('formula').innerHTML = '<tr><th class="scene_desc" colspan="3">入力</th></tr><tr><td class="symbol"><img src="formula_ina.svg" /></td><td>２つの整数を読み込みます。</td><td style="width:100px" class="code"></td></tr><tr><th class="scene_desc" colspan="3">スワップ</th></tr><tr><td class="symbol"><img src="formula_ai.svg" /></td><td>変数に別の変数の値を書き込みます。</td><td style="width:100px" class="code">t &larr; a<br/>a &larr; b<br/>b &larr; t</td></tr><tr><th class="scene_desc" colspan="3">出力</th></tr><tr><td class="symbol"><img src="formula_outa.svg" /></td><td>入れ替わった整数を出力します。</td><td style="width:100px" class="code"></td></tr>';
document.getElementById('scheme').innerHTML = '<tr><td style="text-align:center;width:100"><img src="anim_qr.svg" width="80"/></td><td class="frame"><hr class="separator"/><img height="160" class="frame_svg" src="scheme_step1.svg" /><p class="caption">別の変数から値をコピーして書き込みます。</p></td></tr>';
document.getElementById('scene').innerHTML = '<div><p><b>入力</b><br/><img src="scene_0.svg" /></p></div><div><p><b>スワップ</b><br/><img src="scene_1.svg" /></p></div><div><p><b>出力</b><br/><img src="scene_2.svg" /></p></div>';
document.getElementById('complexity').innerHTML = '';
document.getElementById('prerequisites').innerHTML = '';
MathJax.Hub.Queue(["Typeset",MathJax.Hub]);};