window.onload = function () {
document.getElementById('io_arrow').innerHTML = "&rarr;";
document.getElementById('level').innerHTML = "&#9733; &#9734; ";
document.getElementById('ptitle').innerHTML = "將 2 個已排序序列合併並重新排序";
document.getElementById('ptitle_en').innerHTML = "(Sorting Two Sorted Sequences)";
document.getElementById('input_comment').innerHTML = "前、後 2 個序列都已各自完成排序<ul><li>序列元素數N &le; 100,000</li></ul>";
document.getElementById('output_comment').innerHTML = "合併後且完成升冪排序的序列";
document.getElementById('motivation').innerHTML = "想將 2 個依升冪排序的序列合併在一起，並希望合併後的序列也依升冪排序，該怎麼做才有效率呢？";
document.getElementById('description').innerHTML = "將 2 個升冪排列的序列，合併成 1 個依升冪排列的序列。";
document.getElementById('input_panel').innerHTML = '<img src="../../problems/merge/input.svg" width="340"/>';
document.getElementById('output_panel').innerHTML = '<img src="../../problems/merge/output.svg" width="340"/>';
document.getElementById('algorithm_icon').innerHTML = '<img src="../../icons/algorithms/merge.svg" width="100"/>';
document.getElementById('atitle').innerHTML = "合併";
document.getElementById('atitle_en').innerHTML = "Merge";
document.getElementById('abstract').innerHTML = "合併的操作需要準備 1 個暫存陣列，首先將 2 個已升冪排序過的序列暫存到陣列 T，接著將後半段的序列反轉（變成降冪）。逐一比較 2 個序列最前端的元素，選出元素值較小者，從暫存陣列 T 放回到原陣列 A，當暫存陣列變成空陣列時，就完成兩個序列的合併並依照升冪排列了。";
document.getElementById('explanation').innerHTML = "首先將前、後 2 個已排序陣列的元素都複製到暫存用的陣列中。接著，反轉後半段的序列再進行合併處理，比較前、後段最前端的元素，選出較小者，將其放回原陣列中。由於我們將後半段的順序反轉，因此當前、後其中一段變成空序列時，該段的箭頭將會指向另一段最尾端的元素。";
document.getElementById('note').innerHTML = "若陣列前、後段的元素皆已各自按升冪排序，則整體的排序便能更有效率地完成。由於比較前、後兩段最前端的元素以及複製元素的次數皆為 N 次，因此合併處理的時間複雜度為 O(N)。此外，由於陣列中的所有元素都必須先暫存到另一個陣列中，因此所需的記憶體大小為輸入資料的 2 倍。";
document.getElementById('application').innerHTML = "合併 2 個已排序的序列處理，是進階排序演算法「合併排序法」的基本操作。";
document.getElementById('structure').innerHTML = '<tr><td style="text-align:center;width:100"><img src="../../icons/structures/A1D.svg" /><br/><br/></td><td class="frame">&nbsp;<img height="160" class="frame_svg" valign="middle" src="space_st.svg" />&nbsp;</td></tr><tr><td></td><td class="caption">2 個一維陣列</td></tr>';
document.getElementById('variable').innerHTML = '<tr><th class="scene_desc" colspan="3">資料</th></tr><tr><td class="symbol"><img src="variable_A.svg" /></td><td>整數序列</td><td class="code">A</td></tr><tr><td class="symbol"><img src="variable_T.svg" /></td><td>暫存用的整數陣列</td><td class="code">T</td></tr>';
document.getElementById('formula').innerHTML = '<tr><th class="scene_desc" colspan="3">輸入並暫存資料</th></tr><tr><td class="symbol"><img src="formula_lw.svg" /></td><td>將輸入的資料暫存到另一個陣列。</td><td class="code"></td></tr><tr><td class="symbol"><img src="formula_rw.svg" /></td><td>反轉後半段的序列。</td><td class="code"></td></tr><tr><th class="scene_desc" colspan="3">合併</th></tr><tr><td class="symbol"><img src="formula_select.svg" /></td><td>分別比較位於前、後段序列最前端的元素，並選出較小者。</td><td class="code">if T[i] &le; T[j]:</td></tr><tr><td class="symbol"><img src="formula_k.svg" /></td><td>將選出的元素放回原陣列。</td><td class="code">A[k] &larr; T[?]</td></tr><tr><td class="symbol"><img src="formula_di.svg" /></td><td>指向前半段序列目前的所在位置。</td><td class="code">i</td></tr><tr><td class="symbol"><img src="formula_dj.svg" /></td><td>指向後半段序列目前的所在位置。</td><td class="code">j</td></tr><tr><td class="symbol"><img src="formula_sorted.svg" /></td><td>擴大已排序完成的範圍。</td><td class="code">區間[l, k]</td></tr><tr><th class="scene_desc" colspan="3">輸出</th></tr><tr><td class="symbol"><img src="formula_out.svg" /></td><td>輸出排序完成的序列。</td><td class="code"></td></tr>';
document.getElementById('scheme').innerHTML = '<tr><td style="text-align:center;width:100"><img src="anim_qr.svg" width="80"/></td><td class="frame"><hr class="separator"/><img height="160" class="frame_svg" src="scheme_step1.svg" /><p class="caption">分別比較前、後半段序列，最前端的 2 個元素。</p><hr class="separator"/><img height="160" class="frame_svg" src="scheme_step2.svg" /><p class="caption">將較小的元素放回原陣列，並將箭頭移向下一個元素。</p></td></tr>';
document.getElementById('scene').innerHTML = '<div><p><b class="scene_desc">輸入並暫存資料</b><br/><img src="scene_0.svg" alt="合併 | 輸入並暫存資料" title="合併 | 輸入並暫存資料"/></p></div><div><p><b class="scene_desc">合併</b><br/><img src="scene_1.svg" alt="合併 | 合併" title="合併 | 合併"/></p></div><div><p><b class="scene_desc">輸出</b><br/><img src="scene_2.svg" alt="合併 | 輸出" title="合併 | 輸出"/></p></div>';
document.getElementById('complexity').innerHTML = '<img src="../../../icons/complexity/linear.svg" />';
document.getElementById('prerequisites').innerHTML = '<img src="../../icons/algorithms/reverse.svg" width="60"/>';
MathJax.Hub.Queue(["Typeset",MathJax.Hub]);};